export const transfers = [
  {
    id: 23,
    destination_container_id: 13,
    amount_transferred_unit: "mL",
    source_container_id: 244,
    amount_transferred: 250,
  },
  {
    id: 22,
    destination_container_id: 244,
    amount_transferred_unit: "mL",
    source_container_id: 237,
    amount_transferred: 50,
  },
  {
    id: 24,
    destination_container_id: 244,
    amount_transferred_unit: "mL",
    source_container_id: 237,
    amount_transferred: 200,
  },
  {
    id: 3,
    destination_container_id: 237,
    amount_transferred_unit: "mL",
    source_container_id: 231,
    amount_transferred: 50,
  },
  {
    id: 2,
    destination_container_id: 231,
    amount_transferred_unit: "mL",
    source_container_id: 225,
    amount_transferred: 2,
  },
  {
    id: 1,
    destination_container_id: 225,
    amount_transferred_unit: "colonies",
    source_container_id: 219,
    amount_transferred: 10,
  },
  {
    id: 25,
    destination_container_id: 26,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 26,
    destination_container_id: 39,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 27,
    destination_container_id: 63,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 28,
    destination_container_id: 75,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 29,
    destination_container_id: 87,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 30,
    destination_container_id: 99,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 31,
    destination_container_id: 111,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 32,
    destination_container_id: 51,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 33,
    destination_container_id: 123,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 34,
    destination_container_id: 135,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 35,
    destination_container_id: 147,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 36,
    destination_container_id: 159,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 37,
    destination_container_id: 171,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 38,
    destination_container_id: 183,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 39,
    destination_container_id: 195,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 1372,
    destination_container_id: 1589,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 1384,
    destination_container_id: 1601,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 1396,
    destination_container_id: 1613,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 1408,
    destination_container_id: 1625,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 1420,
    destination_container_id: 1637,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 1432,
    destination_container_id: 1649,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 1444,
    destination_container_id: 1661,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
  {
    id: 1456,
    destination_container_id: 1673,
    amount_transferred_unit: "mL",
    source_container_id: 13,
    amount_transferred: 5,
  },
];

export const transferList = transfers.map((transfer) => {
  return {
    ...transfer,
    type: "emptyEdge",
    source: transfer.source_container_id,
    target: transfer.destination_container_id,
  };
});
